code --install-extension abusaidm.html-snippets
code --install-extension dariofuzinato.vue-peek
code --install-extension dbaeumer.vscode-eslint
code --install-extension discountry.react-redux-react-router-snippets
code --install-extension donjayamanne.githistory
code --install-extension dzannotti.vscode-babel-coloring
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-intellisense
code --install-extension howardzuo.vscode-git-tags
code --install-extension idrabenia.solidity-solhint
code --install-extension jmsv.JavaScriptSnippetsStandard
code --install-extension JuanBlanco.solidity
code --install-extension kisstkondoros.csstriggers
code --install-extension mkaufman.HTMLHint
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension NuclleaR.vscode-extension-auto-import
code --install-extension octref.vetur
code --install-extension prograhammer.tslint-vue
code --install-extension pushqrdx.inline-html
code --install-extension sdras.vue-vscode-snippets
code --install-extension shardulm94.trailing-spaces
code --install-extension shinnn.stylelint
code --install-extension timothymclane.react-redux-es6-snippets
code --install-extension WallabyJs.quokka-vscode
code --install-extension wayou.vscode-todo-highlight
code --install-extension whatwedo.twig
