code --install-extension abusaidm.html-snippets
code --install-extension dariofuzinato.vue-peek
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension dzannotti.vscode-babel-coloring
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension EQuimper.react-native-react-redux
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-intellisense
code --install-extension howardzuo.vscode-git-tags
code --install-extension idrabenia.solidity-solhint
code --install-extension infeng.vscode-react-typescript
code --install-extension jmsv.JavaScriptSnippetsStandard
code --install-extension JuanBlanco.solidity
code --install-extension kisstkondoros.csstriggers
code --install-extension mkaufman.HTMLHint
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension octref.vetur
code --install-extension onecentlin.laravel-blade
code --install-extension PeterJausovec.vscode-docker
code --install-extension pushqrdx.inline-html
code --install-extension sdras.vue-vscode-snippets
code --install-extension shardulm94.trailing-spaces
code --install-extension shinnn.stylelint
code --install-extension WallabyJs.quokka-vscode
code --install-extension wayou.vscode-todo-highlight
code --install-extension whatwedo.twig
code --install-extension xabikos.JavaScriptSnippets
